name: TriNet
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2023.05.30
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.3
  - openssl=1.1.1u
  - pip=23.1.2
  - python=3.8.13
  - readline=8.1.2
  - setuptools=67.8.0
  - sqlite=3.38.5
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - cachetools==5.3.1
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - clang==5.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - et-xmlfile==1.1.0
    - flatbuffers==23.5.26
    - fonttools==4.40.0
    - gast==0.4.0
    - google-auth==2.20.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.54.2
    - h5py==3.1.0
    - idna==3.4
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - jax==0.4.12
    - joblib==1.2.0
    - keras==2.12.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==16.0.0
    - markdown==3.4.3
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - ml-dtypes==0.2.0
    - numpy==1.23.5
    - oauthlib==3.2.2
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - packaging==23.1
    - pandas==2.0.2
    - pillow==9.5.0
    - protobuf==4.23.3
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - six==1.15.0
    - tensorboard==2.12.3
    - tensorboard-data-server==0.7.1
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - typing-extensions==3.7.4.3
    - tzdata==2023.3
    - urllib3==1.26.16
    - werkzeug==2.3.6
    - wrapt==1.12.1
    - xlrd==1.2.0
    - zipp==3.15.0

