name: TriNet
channels:
  - defaults
dependencies:
  - pip
  - python=3.8.13
  - pip:
    - keras==2.12.0
    - matplotlib==3.7.1
    - numpy==1.23.5
    - openpyxl==3.1.2
    - pandas==2.0.2
    - prettytable==3.8.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - tensorflow==2.12.0
    